# ?????? ??
spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: hanna
    password: hanna
    url: jdbc:h2:file:C:/h2Data/240811
    #url: jdbc:h2:mem:testdb;MODE=MySQL #MySQL ?? ??

  # JPA ??
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true

  # H2 ?? ???
  h2:
    console:
      enabled: true