
spring:
  # DB
  datasource:
    driver-class-name: org.h2.Driver
    username: hanna
    password: hanna
    url: jdbc:h2:file:C:/h2Data/240811
    #url: jdbc:h2:mem:testdb;MODE=MySQL #MySQL호환

  # JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: trueD

  # H2
  h2:
    console:
      enabled: true

  # logging
  logging:
    level:
      root: DEBUG
      org.springframework.security: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration